name: setup test
on:
  push:
    branches: [main]
    paths:
      - "scripts/**"
      - ".zshrc"
      - "p10k"
  pull_request:
    branches: [main]
    paths:
      - "scripts/**"
      - ".zshrc"
      - "p10k"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup test
        run: sh ./scripts/setup.sh
